var express = require('express');
var router = express.Router();

const nameList = [
{ 'id': '01', 'term' : 'DevOps', 'desc' : 'DevOps is a set of methods that combines software development and operations to shorten the system’s development phase while still delivering high-quality software. It emphasizes the use of proper communication, collaboration, and automation to achieve a certain goal.', 'ref': 'Vadapalli, S. 2018, DevOps : continuous delivery, integration, and deployment with DevOps : dive into the core DevOps strategies / Sricharan Vadapalli, Packt Publishing, viewed 11 July 2022'},
{ 'id': '02', 'term' : 'Silos', 'desc' : 'Silos it is a term used in organisations wherein the teams insulates themselves from other teams and can cause lack of collaboration.', 'ref': 'Madamanchi, S., 2021, Google Cloud for DevOps Engineers / Madamanchi, Sandeep, Packt Publishing, Accessed: 21 July 2023'},
{ 'id': '03', 'term' : 'CI/CD Pipelines', 'desc' : 'CI/CD Pipelines is a series of methods that must be done in order to deliver a revised version of a program. ', 'ref': 'Madamanchi, S., 2021, Google Cloud for DevOps Engineers / Madamanchi, Sandeep, Packt Publishing, Accessed: 21 July 2023'},
{ 'id': '04', 'term' : 'Microservices', 'desc' : 'Microservices is the main example used within DevOps because they are composed of tiny, discrete software parts that can be readily combined to construct bigger, more complicated software systems. ', 'ref': 'Davis, A. (Software engineer), author. (2021) Bootstrapping microservices with Docker, Kubernetes, and Terraform : a project-based guide. [First edition]. Edited by A. Newmark. Manning Publications. Accessed: 21 July 2023'},
{ 'id': '05', 'term' : 'Inward facing ', 'desc' : 'Inward facing refers to the factors concerning the employees of a certain organisation. ', 'ref': 'Coupland, M., 2021, DevOps Adoption Strategies : Principles, Processes, Tools, and Trends / Coupland, Martyn, Packt Publishing, Accessed: 21 July 2023'},
{ 'id': '06', 'term' : 'Outward facing ', 'desc' : 'Outward facing refers to the factors concerning the customers or the end-user of a certain project.', 'ref': 'Coupland, M., 2021, DevOps Adoption Strategies : Principles, Processes, Tools, and Trends / Coupland, Martyn, Packt Publishing, Accessed: 21 July 2023'},
{ 'id': '07', 'term' : 'Data explosion ', 'desc' : 'Data explosion refers to the level of difficulty in data management due to rapid increase in the amount of data that are generated in the computing systems.', 'ref': 'Sricharan Vadapalli, (2018), DevOps: continuous delivery, integration, and deployment with DevOps: dive into the core DevOps strategies, Accessed: 21 July 2023'},
{ 'id': '08', 'term' : 'In-memory computing', 'desc' : 'In-memory computing refers to the process of relying the calculations to the main memory of the computer itself which make computations very fast. ', 'ref': 'Sricharan Vadapalli, (2018), DevOps: continuous delivery, integration, and deployment with DevOps: dive into the core DevOps strategies, Accessed: 21 July 2023'},
{ 'id': '09', 'term' : 'Docker', 'desc' : 'Docker is a more efficient and portable open source tool that is similar to Virtual Machines. It is mainly used to “pack” an application and all its dependencies.', 'ref': 'Sricharan Vadapalli, (2018), DevOps: continuous delivery, integration, and deployment with DevOps: dive into the core DevOps strategies, Accessed: 21 July 2023'},
{ 'id': '10', 'term' : 'Kubernete', 'desc' : 'Kubernetes is another open source tool used to help better organise the Docker containers', 'ref': 'Sricharan Vadapalli, (2018), DevOps: continuous delivery, integration, and deployment with DevOps: dive into the core DevOps strategies, Accessed: 21 July 2023'},
{ 'id': '11', 'term' : 'Enterprise architecture', 'desc' : 'Enterprise architecture refers to the starting point and the part where the business goals are set define how these goals will be met.', 'ref': 'Mulder, J author. 2021, Enterprise DevOps for Architects, 1st edition., Packt Publishing, Accessed: 11 August 2023'},
{ 'id': '12', 'term' : 'Business demand', 'desc' : 'Business demand refers to the understanding of the requirements for a product that is needed to be delivered and made. The said requirements are set by the end-users.', 'ref': 'Mulder, J author. 2021, Enterprise DevOps for Architects, 1st edition., Packt Publishing, Accessed: 11 August 2023'},
{ 'id': '13', 'term' : 'Definition of Done (DoD)', 'desc' : 'Definition of Done (DoD) refers to the acceptance criteria, and when all the requirements are met which is a key of any user story.', 'ref': 'Mulder, J author. 2021, Enterprise DevOps for Architects, 1st edition., Packt Publishing, Accessed: 11 August 2023'},
{ 'id': '14', 'term' : 'Continuous integration (CI)', 'desc' : 'Continuous integration (CI) means enabling the developers to collaborate on the same code at the same time.', 'ref': 'Mulder, J author. 2021, Enterprise DevOps for Architects, 1st edition., Packt Publishing, Accessed: 11 August 2023'},
{ 'id': '15', 'term' : 'Continuous delivery (CD)', 'desc' : 'Continuous delivery (CD) refers to the automated distribution of software to testing environments. The ultimate objective of CD is to totally automate the development of software.', 'ref': 'Mulder, J author. 2021, Enterprise DevOps for Architects, 1st edition., Packt Publishing, Accessed: 11 August 2023'},
{ 'id': '16', 'term' : 'Feedback loop', 'desc' : 'Feedback loop refers to a part of a system when all or a portion of the output is sent back into the input.', 'ref': 'Mulder, J author. 2021, Enterprise DevOps for Architects, 1st edition., Packt Publishing, Accessed: 11 August 2023'},
{ 'id': '17', 'term' : 'The Open Group Architecture Framework (TOGAF)', 'desc' : 'The Open Group Architecture Framework (TOGAF) is globally accepted as the standard for enterprise and business architecture.', 'ref': 'Mulder, J author. 2021, Enterprise DevOps for Architects, 1st edition., Packt Publishing, Accessed: 11 August 2023'},
{ 'id': '18', 'term' : 'Interoperability', 'desc' : 'Interoperability refers to the capacity of computer systems or software to share and utilise data.', 'ref': 'Mulder, J author. 2021, Enterprise DevOps for Architects, 1st edition., Packt Publishing, Accessed: 11 August 2023'},
{ 'id': '19', 'term' : 'Cumbersome', 'desc' : 'Cumbersome refers to being slow and inefficient. It is the effect of monitoring and reporting every metric that is included in any contract.', 'ref': 'Mulder, J author. 2021, Enterprise DevOps for Architects, 1st edition., Packt Publishing, Accessed: 11 August 2023'},
{ 'id': '20', 'term' : 'The VOICE Model', 'desc' : 'The VOICE Model stands for Value, Objectives, Indicators, Confidence, and Experience. It is defined by Sogeti which is an IT Company which addresses how DevOps teams need to deliver value to the end-user.', 'ref': 'Mulder, J author. 2021, Enterprise DevOps for Architects, 1st edition., Packt Publishing, Accessed: 11 August 2023'},
{ 'id': '21', 'term' : 'Containers', 'desc' : 'Containers give us a permission to virtualise the hardware and the operating system and allows to divide the resources from one computer and share it to other services. Often compared to virtual machines.', 'ref': 'Mulder, J author. 2021, Enterprise DevOps for Architects, 1st edition., Packt Publishing, Accessed: 23 August 2023'},
{ 'id': '22', 'term' : 'Immutable', 'desc' : 'Immutable refers to being incapable of being modified which applies to the bootable snapshots of a server.', 'ref': 'Mulder, J author. 2021, Enterprise DevOps for Architects, 1st edition., Packt Publishing, Accessed: 23 August 2023'},
{ 'id': '23', 'term' : 'Standardasing environments ', 'desc' : 'Definition of Done (DoD) refers to the acceptance criteria, and when all the requirements are met which is a key of any user story.', 'ref': 'Mulder, J author. 2021, Enterprise DevOps for Architects, 1st edition., Packt Publishing, Accessed: 23 August 2023'},
{ 'id': '24', 'term' : 'WSL', 'desc' : 'WSL kernel interface refers to a compatibility layer for running Linux binaries natively in a console environment on Windows which is needed to be updated to able to use Docker.', 'ref': 'Mulder, J author. 2021, Enterprise DevOps for Architects, 1st edition., Packt Publishing, Accessed: 23 August 2023'},
{ 'id': '25', 'term' : 'Dockerfile', 'desc' : 'Dockerfile refers to a script file containing guidelines on how to build the image created by Docker.', 'ref': 'Mulder, J author. 2021, Enterprise DevOps for Architects, 1st edition., Packt Publishing, Accessed: 23 August 2023'},
{ 'id': '26', 'term' : 'Base image ', 'desc' : 'Base image refers to where the new image is derived from.', 'ref': 'Mulder, J author. 2021, Enterprise DevOps for Architects, 1st edition., Packt Publishing, Accessed: 23 August 2023'},
{ 'id': '27', 'term' : 'Docker compose ', 'desc' : 'Docker compose is another tool to conveniently build, run and manage microservices in development.', 'ref': 'Mulder, J author. 2021, Enterprise DevOps for Architects, 1st edition., Packt Publishing, Accessed: 23 August 2023'},
{ 'id': '28', 'term' : 'Docker compose file ', 'desc' : 'Docker compose file refers to the script that explains how to build an application out of various Docker containers.', 'ref': 'Mulder, J author. 2021, Enterprise DevOps for Architects, 1st edition., Packt Publishing, Accessed: 23 August 2023'},
{ 'id': '29', 'term' : 'YAML', 'desc' : 'YAML refers to the file format of Docker Compose. Configuration files are frequently written in YAML, which a human-readable data serialisation language.', 'ref': 'Mulder, J author. 2021, Enterprise DevOps for Architects, 1st edition., Packt Publishing, Accessed: 23 August 2023'},
{ 'id': '30', 'term' : 'Azure storage ', 'desc' : 'Azure storage refers to the Microsoft azure service for hosting private or public files in the cloud.', 'ref': 'Mulder, J author. 2021, Enterprise DevOps for Architects, 1st edition., Packt Publishing, Accessed: 23 August 2023'},

];

/* GET home page. */
router.get('/', function(req, res, next) {
  res.render('index', { title: 'SIT722 DevOps Glossary - S222509548', sub: ' my website showing a collection of DevOps terms and their descriptions', names: nameList });
});

module.exports = router;
